### ISSUE TITLE
Is it a 24/7 server?

### ISSUE THREAD

**Issue by Dwaitp** [itzkrishop/create-mc-server#1]

**Comment by itzkrishop** [comment]
As long as you open the codespace in your browser it will remain online ,👍

**Comment by Dwaitp** [comment]
K, thanks!
Thanks,
Dwait

**Comment by KaydenPlayzOP** [comment]
@itzkrishop can i put vps or IN node??

**Comment by gamerwaves** [comment]
> [@itzkrishop](https://github.com/itzkrishop) can i put vps or IN node??

i think vps only idk

**Comment by KaydenPlayzOP** [comment]
@itzkrishop neofetch vps?
